SELECT
	SUM(IF(sj.product = 'Bakerstar Biru Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_biru,
	SUM(IF(sj.product = 'Bakerstar Emas Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_emas,
	SUM(IF(sj.product = 'Bakerstar Hijau Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_hijau,
	SUM(IF(sj.product = 'Bakerstar Jingga Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_jingga,
	SUM(IF(sj.product = 'Bakerstar Kuning Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_kuning,
	SUM(IF(sj.product = 'Bakerstar Merah Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_merah,
	SUM(IF(sj.product = 'Bakerstar Ungu Wheat Flour @25kg', sj.bag, 0)) AS bakerstar_ungu,
	SUM(IF(sj.product = 'Cerestar Bread Flour @25kg', sj.bag, 0)) AS cerestar_bread,
	SUM(IF(sj.product = 'Cerestar Coklat Flour @25kg', sj.bag, 0)) AS cerestar_coklat,
	SUM(IF(sj.product = 'Cerestar Hijau Flour @25kg', sj.bag, 0)) AS cerestar_hijau,
	SUM(IF(sj.product = 'Cerestar Kuning Flour @25kg', sj.bag, 0)) AS cerestar_kuning,
	SUM(IF(sj.product = 'Cerestar Perunggu Flour @25kg', sj.bag, 0)) AS cerestar_perunggu,
	SUM(IF(sj.product = 'Cerestar SPC Flour @25kg', sj.bag, 0)) AS cerestar_spc,
	SUM(IF(sj.product = 'Dragonfly Wheat Flour @25kg', sj.bag, 0)) AS dragonfly,
	SUM(IF(sj.product = 'Dragonfly Wheat Flour @25 kg (R)', sj.bag, 0)) AS dragonfly_r,
	SUM(IF(sj.product = 'Falcon Biru Wheat Flour @25kg', sj.bag, 0)) AS falcon_biru,
	SUM(IF(sj.product = 'Falcon Coklat Wheat Flour @25kg', sj.bag, 0)) AS falcon_coklat,
	SUM(IF(sj.product = 'Falcon Emas Wheat Flour @25kg', sj.bag, 0)) AS falcon_emas,
	SUM(IF(sj.product = 'Falcon Hijau Wheat Flour @25kg', sj.bag, 0)) AS falcon_hijau,
	SUM(IF(sj.product = 'Falcon Hitam Wheat Flour @25kg', sj.bag, 0)) AS falcon_hitam,
	SUM(IF(sj.product = 'Falcon Jingga Wheat Flour @25kg', sj.bag, 0)) AS falcon_jingga,
	SUM(IF(sj.product = 'Falcon Kuning Wheat Flour @25kg', sj.bag, 0)) AS falcon_kuning,
	SUM(IF(sj.product = 'Falcon Magenta Wheat Flour @25kg', sj.bag, 0)) AS falcon_magenta,
	SUM(IF(sj.product = 'Falcon Merah Wheat Flour @25kg', sj.bag, 0)) AS falcon_merah,
	SUM(IF(sj.product = 'Falcon Nila Wheat Flour @25kg', sj.bag, 0)) AS falcon_nila,
	SUM(IF(sj.product = 'Falcon Pelangi Wheat Flour @25kg', sj.bag, 0)) AS falcon_pelangi,
	SUM(IF(sj.product = 'Falcon Perak Wheat Flour @25kg', sj.bag, 0)) AS falcon_perak,
	SUM(IF(sj.product = 'Falcon Perunggu Wheat Flour @25kg', sj.bag, 0)) AS falcon_perunggu,
	SUM(IF(sj.product = 'Falcon Serba Guna (E) Wheat Flour @10x1 kg', sj.bag, 0)) AS falcon_serbaguna_e,
	SUM(IF(sj.product = 'Falcon Serba Guna (P) Wheat Flour @10x1 kg', sj.bag, 0)) AS falcon_serbaguna_p,
	SUM(IF(sj.product = 'Falcon Ungu Wheat Flour @25kg', sj.bag, 0)) AS falcon_ungu,
	SUM(IF(sj.product = 'Fama Gold Bakers Flour @10kg', sj.bag, 0)) AS fama_bakers_10,
	SUM(IF(sj.product = 'Fama Gold Bakers Flour @25kg', sj.bag, 0)) AS fama_bakers,
	SUM(IF(sj.product = 'Fama Gold Bakers Flour @51kg', sj.bag, 0)) AS fama_bakers_51,
	SUM(IF(sj.product = 'Fama Gold Biscuit Flour @51kg', sj.bag, 0)) AS fama_biscuit_51,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @10kg', sj.bag, 0)) AS fama_plain_10,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @10x1 kg', sj.bag, 0)) AS fama_plain_10_1,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @25kg', sj.bag, 0)) AS fama_plain,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @51kg', sj.bag, 0)) AS fama_plain_51,
	SUM(IF(sj.product = 'Fama Gold Self Raising Flour @10x1 kg', sj.bag, 0)) AS fama_self,
	SUM(IF(sj.product = 'Sample Wheat Flour', sj.bag, 0)) AS sample,
	SUM(IF(sj.product = 'Seagull Wheat Flour @25kg', sj.bag, 0)) AS seagull,
	SUM(IF(sj.product = 'Falcon Nila Wheat Flour (Bulk)', sj.bag, 0)) AS falcon_nila_bulk,
	SUM(IF(sj.product = 'Falcon Pelangi Wheat Flour (Bulk)', sj.bag, 0)) AS falcon_pelangi_bulk,
	SUM(IF(sj.product = 'Fama Gold Self Raising Flour (Bulk)', sj.bag, 0)) AS fama_self_bulk,

	SUM(IF(sj.product = 'Bakerstar Biru Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_biru,
	SUM(IF(sj.product = 'Bakerstar Emas Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_emas,
	SUM(IF(sj.product = 'Bakerstar Hijau Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_hijau,
	SUM(IF(sj.product = 'Bakerstar Jingga Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_jingga,
	SUM(IF(sj.product = 'Bakerstar Kuning Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_kuning,
	SUM(IF(sj.product = 'Bakerstar Merah Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_merah,
	SUM(IF(sj.product = 'Bakerstar Ungu Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_bakerstar_ungu,
	SUM(IF(sj.product = 'Cerestar Bread Flour @25kg', sj.bag * p.weight, 0)) AS ton_cerestar_bread,
	SUM(IF(sj.product = 'Cerestar Coklat Flour @25kg', sj.bag * p.weight, 0)) AS ton_cerestar_coklat,
	SUM(IF(sj.product = 'Cerestar Hijau Flour @25kg', sj.bag * p.weight, 0)) AS ton_cerestar_hijau,
	SUM(IF(sj.product = 'Cerestar Kuning Flour @25kg', sj.bag * p.weight, 0)) AS ton_cerestar_kuning,
	SUM(IF(sj.product = 'Cerestar Perunggu Flour @25kg', sj.bag * p.weight, 0)) AS ton_cerestar_perunggu,
	SUM(IF(sj.product = 'Cerestar SPC Flour @25kg', sj.bag * p.weight, 0)) AS ton_cerestar_spc,
	SUM(IF(sj.product = 'Dragonfly Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_dragonfly,
	SUM(IF(sj.product = 'Dragonfly Wheat Flour @25 kg (R)', sj.bag * p.weight, 0)) AS ton_dragonfly_r,
	SUM(IF(sj.product = 'Falcon Biru Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_biru,
	SUM(IF(sj.product = 'Falcon Coklat Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_coklat,
	SUM(IF(sj.product = 'Falcon Emas Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_emas,
	SUM(IF(sj.product = 'Falcon Hijau Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_hijau,
	SUM(IF(sj.product = 'Falcon Hitam Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_hitam,
	SUM(IF(sj.product = 'Falcon Jingga Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_jingga,
	SUM(IF(sj.product = 'Falcon Kuning Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_kuning,
	SUM(IF(sj.product = 'Falcon Magenta Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_magenta,
	SUM(IF(sj.product = 'Falcon Merah Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_merah,
	SUM(IF(sj.product = 'Falcon Nila Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_nila,
	SUM(IF(sj.product = 'Falcon Pelangi Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_pelangi,
	SUM(IF(sj.product = 'Falcon Perak Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_perak,
	SUM(IF(sj.product = 'Falcon Perunggu Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_perunggu,
	SUM(IF(sj.product = 'Falcon Serba Guna (E) Wheat Flour @10x1 kg', sj.bag * p.weight, 0)) AS ton_falcon_serbaguna_e,
	SUM(IF(sj.product = 'Falcon Serba Guna (P) Wheat Flour @10x1 kg', sj.bag * p.weight, 0)) AS ton_falcon_serbaguna_p,
	SUM(IF(sj.product = 'Falcon Ungu Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_falcon_ungu,
	SUM(IF(sj.product = 'Fama Gold Bakers Flour @10kg', sj.bag * p.weight, 0)) AS ton_fama_bakers_10,
	SUM(IF(sj.product = 'Fama Gold Bakers Flour @25kg', sj.bag * p.weight, 0)) AS ton_fama_bakers,
	SUM(IF(sj.product = 'Fama Gold Bakers Flour @51kg', sj.bag * p.weight, 0)) AS ton_fama_bakers_51,
	SUM(IF(sj.product = 'Fama Gold Biscuit Flour @51kg', sj.bag * p.weight, 0)) AS ton_fama_biscuit_51,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @10kg', sj.bag * p.weight, 0)) AS ton_fama_plain_10,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @10x1 kg', sj.bag * p.weight, 0)) AS ton_fama_plain_10_1,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @25kg', sj.bag * p.weight, 0)) AS ton_fama_plain,
	SUM(IF(sj.product = 'Fama Gold Plain Flour @51kg', sj.bag * p.weight, 0)) AS ton_fama_plain_51,
	SUM(IF(sj.product = 'Fama Gold Self Raising Flour @10x1 kg', sj.bag * p.weight, 0)) AS ton_fama_self,
	SUM(IF(sj.product = 'Sample Wheat Flour', sj.bag * p.weight, 0)) AS ton_sample,
	SUM(IF(sj.product = 'Seagull Wheat Flour @25kg', sj.bag * p.weight, 0)) AS ton_seagull,
	SUM(IF(t.productname = 'Falcon Nila Wheat Flour (Bulk)', t.netto, 0)) AS ton_falcon_nila_bulk,
	SUM(IF(t.productname = 'Falcon Pelangi Wheat Flour (Bulk)', t.netto, 0)) AS ton_falcon_pelangi_bulk,
	SUM(IF(t.productname = 'Fama Gold Self Raising Flour (Bulk)', t.netto, 0)) AS ton_fama_self_bulk,


	sum(sj.bag) as total_bag,
	sum(sj.bag * p.weight) as total_tonase_bag,
	0 as total_tonase_bulk,
	t.id_transaction as id_transaction,
	date(t.date2) as dates
from suratjalan as sj
join transactions t on t.id_transaction = sj.id_transaction
join product p on p.id_product = t.id_product
and t.ticket2 is not null
and t.id_product in (1,2,3,8,13)
and t.sales = 'SALES'
group by t.date2

UNION ALL

select 
	0 as bakerstar_biru,
	0 as bakerstar_emas,
	0 as bakerstar_hijau,
	0 as bakerstar_jingga,
	0 as bakerstar_kuning,
	0 as bakerstar_merah,
	0 as bakerstar_ungu,
	0 as cerestar_bread,
	0 as cerestar_coklat,
	0 as cerestar_hijau,
	0 as cerestar_kuning,
	0 as cerestar_perunggu,
	0 as cerestar_spc,
	0 as dragonfly,
	0 as dragonfly_r,
	0 as falcon_biru,
	0 as falcon_coklat,
	0 as falcon_emas,
	0 as falcon_hijau,
	0 as falcon_hitam,
	0 as falcon_jingga,
	0 as falcon_kuning,
	0 as falcon_magenta,
	0 as falcon_merah,
	0 as falcon_nila,
	0 as falcon_pelangi,
	0 as falcon_perak,
	0 as falcon_perunggu,
	0 as falcon_serbaguna_e,
	0 as falcon_serbaguna_p,
	0 as falcon_ungu,
	0 as fama_bakers_10,
	0 as fama_bakers,
	0 as fama_bakers_51,
	0 as fama_biscuit_51,
	0 as fama_plain_10,
	0 as fama_plain_10_1,
	0 as fama_plain,
	0 as fama_plain_51,
	0 as fama_self,
	0 as sample,
	0 as seagull,
	0 as falcon_nila_bulk,
	0 as falcon_pelangi_bulk,
	0 as fama_self_bulk,
	0 as ton_bakerstar_biru,
	0 as ton_bakerstar_emas,
	0 as ton_bakerstar_hijau,
	0 as ton_bakerstar_jingga,
	0 as ton_bakerstar_kuning,
	0 as ton_bakerstar_merah,
	0 as ton_bakerstar_ungu,
	0 as ton_cerestar_bread,
	0 as ton_cerestar_coklat,
	0 as ton_cerestar_hijau,
	0 as ton_cerestar_kuning,
	0 as ton_cerestar_perunggu,
	0 as ton_cerestar_spc,
	0 as ton_dragonfly,
	0 as ton_dragonfly_r,
	0 as ton_falcon_biru,
	0 as ton_falcon_coklat,
	0 as ton_falcon_emas,
	0 as ton_falcon_hijau,
	0 as ton_falcon_hitam,
	0 as ton_falcon_jingga,
	0 as ton_falcon_kuning,
	0 as ton_falcon_magenta,
	0 as ton_falcon_merah,
	0 as ton_falcon_nila,
	0 as ton_falcon_pelangi,
	0 as ton_falcon_perak,
	0 as ton_falcon_perunggu,
	0 as ton_falcon_serbaguna_e,
	0 as ton_falcon_serbaguna_p,
	0 as ton_falcon_ungu,
	0 as ton_fama_bakers_10,
	0 as ton_fama_bakers,
	0 as ton_fama_bakers_51,
	0 as ton_fama_biscuit_51,
	0 as ton_fama_plain_10,
	0 as ton_fama_plain_10_1,
	0 as ton_fama_plain,
	0 as ton_fama_plain_51,
	0 as ton_fama_self,
	0 as ton_sample,
	0 as ton_seagull,
	SUM(IF(t.productname = 'Falcon Nila Wheat Flour (Bulk)', t.netto, 0)) AS ton_falcon_nila_bulk,
	SUM(IF(t.productname = 'Falcon Pelangi Wheat Flour (Bulk)', t.netto, 0)) AS ton_falcon_pelangi_bulk,
	SUM(IF(t.productname = 'Fama Gold Self Raising Flour (Bulk)', t.netto, 0)) AS ton_fama_self_bulk,
	0 as total_bag,
	0 as total_tonase_bag,
	sum(t.netto) as total_tonase_bulk,
	t.id_transaction as id_transaction,
	date(t.date2) as dates
from transactions t
join product p on p.id_product = t.id_product
and t.ticket2 is not null
and t.id_product in (8)
and t.sales = 'SALES'
group by t.date2 




bakerstar_biru,
bakerstar_emas,
bakerstar_hijau,
bakerstar_jingga,
bakerstar_kuning,
bakerstar_merah,
bakerstar_ungu,
cerestar_bread,
cerestar_coklat,
cerestar_hijau,
cerestar_kuning,
cerestar_perunggu,
cerestar_spc,
dragonfly,
dragonfly_r,
falcon_biru,
falcon_coklat,
falcon_emas,
falcon_hijau,
falcon_hitam,
falcon_jingga,
falcon_kuning,
falcon_magenta,
falcon_merah,
falcon_nila,
falcon_pelangi,
falcon_perak,
falcon_perunggu,
falcon_serbaguna_e,
falcon_serbaguna_p,
falcon_ungu,
fama_bakers_10,
fama_bakers,
fama_bakers_51,
fama_biscuit_51,
fama_plain_10,
fama_plain_10_1,
fama_plain,
fama_plain_51,
fama_self,
sample,
seagull,
falcon_nila_bulk,
falcon_pelangi_bulk,
fama_self_bulk,
ton_bakerstar_biru,
ton_bakerstar_emas,
ton_bakerstar_hijau,
ton_bakerstar_jingga,
ton_bakerstar_kuning,
ton_bakerstar_merah,
ton_bakerstar_ungu,
ton_cerestar_bread,
ton_cerestar_coklat,
ton_cerestar_hijau,
ton_cerestar_kuning,
ton_cerestar_perunggu,
ton_cerestar_spc,
ton_dragonfly,
ton_dragonfly_r,
ton_falcon_biru,
ton_falcon_coklat,
ton_falcon_emas,
ton_falcon_hijau,
ton_falcon_hitam,
ton_falcon_jingga,
ton_falcon_kuning,
ton_falcon_magenta,
ton_falcon_merah,
ton_falcon_nila,
ton_falcon_pelangi,
ton_falcon_perak,
ton_falcon_perunggu,
ton_falcon_serbaguna_e,
ton_falcon_serbaguna_p,
ton_falcon_ungu,
ton_fama_bakers_10,
ton_fama_bakers,
ton_fama_bakers_51,
ton_fama_biscuit_51,
ton_fama_plain_10,
ton_fama_plain_10_1,
ton_fama_plain,
ton_fama_plain_51,
ton_fama_self,
ton_sample,
ton_seagull,
ton_falcon_nila_bulk,
ton_falcon_pelangi_bulk,
ton_fama_self_bulk,




BAKERSTAR BIRU	BAKERSTAR EMAS	BAKERSTAR HIJAU	BAKERSTAR JINGGA	BAKERSTAR KUNING	BAKERSTAR MERAH	BAKERSTAR UNGU	CERESTAR BREAD	CERESTAR COKLAT	CERESTAR HIJAU	CERESTAR KUNING	CERESTAR PERUNGGU	CERESTAR SPC	DRAGONFLY	DRAGONFLY (R)	FALCON BIRU	FALCON COKLAT	FALCON EMAS	FALCON HIJAU	FALCON HITAM	FALCON JINGGA	FALCON KUNING	FALCON MAGENTA	FALCON MERAH	FALCON NILA	FALCON PELANGI	FALCON PERAK	FALCON PERUNGGU	FALCON SERBAGUNA (E)	FALCON SERBAGUNA (P)	FALCON UNGU	FAMA BAKERS	FAMA BAKERS 51KG	FAMA BISCUIT 51KG	FAMA PLAIN 10KG	FAMA PLAIN 10X1KG	FAMA PLAIN	FAMA PLAIN 51KG	FAMA SELF	SAMPLE	SEAGULL
